[package]
name = "eureka"
version = "1.0.0"
authors = ["Simon Egersand <s.egersand@gmail.com>"]
description = "CLI tool to input and store your ideas without leaving the terminal"
license = "MIT"
exclude = [
    "assets/*",
]

[dependencies]
clap = "~2.27.0"
serde = "~0.8"
serde_derive = "~0.8"
serde_json = "~0.8"
text_io = "~0.1.5"
clippy = {version = "*", optional = true}

[features]
default = []

