[package]
name = "eureka"
version = "1.0.0"
authors = ["Simon Egersand <s.egersand@gmail.com>"]
description = "CLI tool to input and store your ideas without leaving the terminal"
categories = ["command-line-interface", "command-line-utilities", "productivity"]
documentation = "https://github.com/simeg/eureka/blob/master/README.md"
homepage = "https://github.com/simeg/eureka"
keywords = ["command-line-tool", "cli", "productivity"]
repository = "https://github.com/simeg/eureka"
readme = "README.md"
license = "MIT"
exclude = [
    "assets/*",
]

[dependencies]
clap = "~2.27.0"
serde = "~0.8"
serde_derive = "~0.8"
serde_json = "~0.8"
text_io = "~0.1.5"
clippy = {version = "0.0.175", optional = true}

[features]
default = []

